### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by trevorm7** [FACT0RN/factoring#23]
I used the docker run command and get this:

> 2023-08-30 21:12:36 Level: 4 primes: 16  ok Time: 0.000006
2023-08-30 21:12:36 Level: 5 primes: 32  ok Time: 0.000002
2023-08-30 21:12:36 Level: 6 primes: 64  ok Time: 0.000003
2023-08-30 21:12:36 Level: 7 primes: 128  ok Time: 0.000002
2023-08-30 21:12:36 Level: 8 primes: 256  ok Time: 0.000005
2023-08-30 21:12:36 Level: 9 primes: 512  ok Time: 0.000005
2023-08-30 21:12:36 Level: 10 primes: 1024  ok Time: 0.000004
2023-08-30 21:12:36 Level: 11 primes: 2048  ok Time: 0.000008
2023-08-30 21:12:36 Level: 12 primes: 4096  ok Time: 0.000019
2023-08-30 21:12:36 Level: 13 primes: 8192  ok Time: 0.000038
2023-08-30 21:12:36 Level: 14 primes: 16384  ok Time: 0.000075
2023-08-30 21:12:36 Level: 15 primes: 32768  ok Time: 0.000174
2023-08-30 21:12:36 Level: 16 primes: 65536  ok Time: 0.000438
2023-08-30 21:12:36 Level: 17 primes: 131072  ok Time: 0.001132
2023-08-30 21:12:36 Level: 18 primes: 262144  ok Time: 0.002829
2023-08-30 21:12:36 Level: 19 primes: 524288  ok Time: 0.006860
2023-08-30 21:12:36 Level: 20 primes: 1048576  ok Time: 0.016285
2023-08-30 21:12:36 Level: 21 primes: 2097152  ok Time: 0.037373
2023-08-30 21:12:36 Level: 22 primes: 4194304  ok Time: 0.086988
2023-08-30 21:12:36 Level: 23 primes: 8388608  ok Time: 0.213693
2023-08-30 21:12:37 Level: 24 primes: 16777216  ok Time: 0.482845
2023-08-30 21:12:38 Level: 25 primes: 33554432  ok Time: 1.141875
2023-08-30 21:12:40 Level: 26 primes: 67108864  ok Time: 2.632199
2023-08-30 21:12:46 Level: 27 primes: 134217728  ok Time: 5.845222
2023-08-30 21:12:46 [+] SCRIPTPUBKEY: 0014673b05596068ab95e101b4a8e091cef2b2e411b9
2023-08-30 21:12:46 Traceback (most recent call last):
2023-08-30 21:12:46   File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
2023-08-30 21:12:46     h.request(req.get_method(), req.selector, req.data, headers,
2023-08-30 21:12:46   File "/usr/lib/python3.10/http/client.py", line 1283, in request
2023-08-30 21:12:46     self._send_request(method, url, body, headers, encode_chunked)
2023-08-30 21:12:46   File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
2023-08-30 21:12:46     self.endheaders(body, encode_chunked=encode_chunked)
2023-08-30 21:12:46   File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
2023-08-30 21:12:46     self._send_output(message_body, encode_chunked=encode_chunked)
2023-08-30 21:12:46   File "/usr/lib/python3.10/http/client.py", line 1038, in _send_output
2023-08-30 21:12:46     self.send(msg)
2023-08-30 21:12:46   File "/usr/lib/python3.10/http/client.py", line 976, in send
2023-08-30 21:12:46     self.connect()
2023-08-30 21:12:46   File "/usr/lib/python3.10/http/client.py", line 942, in connect
2023-08-30 21:12:46     self.sock = self._create_connection(
2023-08-30 21:12:46   File "/usr/lib/python3.10/socket.py", line 845, in create_connection
2023-08-30 21:12:46     raise err
2023-08-30 21:12:46   File "/usr/lib/python3.10/socket.py", line 833, in create_connection
2023-08-30 21:12:46     sock.connect(sa)
2023-08-30 21:12:46 ConnectionRefusedError: [Errno 111] Connection refused
2023-08-30 21:12:46 
2023-08-30 21:12:46 During handling of the above exception, another exception occurred:
2023-08-30 21:12:46 
2023-08-30 21:12:46 Traceback (most recent call last):
2023-08-30 21:12:46   File "/tmp/factoring/python/FACTOR.py", line 56, in <module>
2023-08-30 21:12:46     mine()
2023-08-30 21:12:46   File "/tmp/factoring/python/FACTOR.py", line 51, in mine
2023-08-30 21:12:46     if B.mine( mine_latest_block = True, scriptPubKey = SCRIPTPUBKEY ):
2023-08-30 21:12:46   File "/tmp/factoring/python/lib/blockchain.py", line 234, in mine
2023-08-30 21:12:46     block = self.get_next_block_to_work_on()
2023-08-30 21:12:46   File "/tmp/factoring/python/lib/blockchain.py", line 79, in get_next_block_to_work_on
2023-08-30 21:12:46     blocktemplate      = rpc_getblocktemplate()
2023-08-30 21:12:46   File "/tmp/factoring/python/lib/rpc.py", line 50, in rpc_getblocktemplate
2023-08-30 21:12:46     return rpc("getblocktemplate", [{"rules": ["segwit"]}])
2023-08-30 21:12:46   File "/tmp/factoring/python/lib/rpc.py", line 33, in rpc
2023-08-30 21:12:46     with urllib.request.urlopen(request) as f:
2023-08-30 21:12:46   File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
2023-08-30 21:12:46     return opener.open(url, data, timeout)
2023-08-30 21:12:46   File "/usr/lib/python3.10/urllib/request.py", line 519, in open
2023-08-30 21:12:46     response = self._open(req, data)
2023-08-30 21:12:46   File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
2023-08-30 21:12:46     result = self._call_chain(self.handle_open, protocol, protocol +
2023-08-30 21:12:46   File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
2023-08-30 21:12:46     result = func(*args)
2023-08-30 21:12:46   File "/usr/lib/python3.10/urllib/request.py", line 1377, in http_open
2023-08-30 21:12:46     return self.do_open(http.client.HTTPConnection, req)
2023-08-30 21:12:46   File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
2023-08-30 21:12:46     raise URLError(err)
2023-08-30 21:12:46 urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

I'm running Docker using WSL and I'm running the node on the same computer in WSL with Ubuntu. I see no option to specify an RPC IP address or port, so I have no idea what it's trying to connect to.

**Comment by auerswaldg** [comment]
I have similar issue but you seem to get further mine crashes out here:
`Level: 4 primes: 16  ok Time: 0.000007
Level: 5 primes: 32  ok Time: 0.000004
Level: 6 primes: 64  ok Time: 0.000002
Level: 7 primes: 128  ok Time: 0.000002
Level: 8 primes: 256  ok Time: 0.000014
Level: 9 primes: 512  ok Time: 0.000003
Level: 10 primes: 1024  ok Time: 0.000005
Level: 11 primes: 2048  ok Time: 0.000010
Level: 12 primes: 4096  ok Time: 0.000019
Level: 13 primes: 8192  ok Time: 0.000036
Level: 14 primes: 16384  ok Time: 0.000086
Level: 15 primes: 32768  ok Time: 0.000236
Level: 16 primes: 65536  ok Time: 0.000587
Level: 17 primes: 131072  ok Time: 0.001570
Level: 18 primes: 262144  ok Time: 0.004230
Level: 19 primes: 524288  ok Time: 0.010466
Level: 20 primes: 1048576  ok Time: 0.035068
Level: 21 primes: 2097152  ok Time: 0.099717
Level: 22 primes: 4194304  ok Time: 0.141856
Level: 23 primes: 8388608  ok Time: 0.318544
Level: 24 primes: 16777216  ok Time: 0.739152
Level: 25 primes: 33554432  ok Time: 1.724480
Level: 26 primes: 67108864  ok Time: 4.047787
Level: 27 primes: 134217728  ok Time: 9.547775
[+] SCRIPTPUBKEY: 00141fa5c697f2e0c9469ccfa288b8dac3867896accf
Traceback (most recent call last):
  File "/tmp/factoring/python/FACTOR.py", line 56, in <module>
    mine()
  File "/tmp/factoring/python/FACTOR.py", line 51, in mine
    if B.mine( mine_latest_block = True, scriptPubKey = SCRIPTPUBKEY ):
  File "/tmp/factoring/python/lib/blockchain.py", line 235, in mine
    block = self.get_next_block_to_work_on()
  File "/tmp/factoring/python/lib/blockchain.py", line 80, in get_next_block_to_work_on
    blocktemplate      = rpc_getblocktemplate()
  File "/tmp/factoring/python/lib/rpc.py", line 48, in rpc_getblocktemplate
    return rpc("getblocktemplate", [{"rules": ["segwit"]}])
  File "/tmp/factoring/python/lib/rpc.py", line 33, in rpc
    with urllib.request.urlopen(request) as f:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Unauthorized
`

**Comment by ReverseControl** [comment]
The first issue is a network issue. I don't use WSL on Windows so I cannot help you there. Folks in the Discord have solved this before though. They can help. The second issue is a credentials problem. Follow the instructions. Create the config file and follow the rest and it will get fixed.
